### ISSUE TITLE
rebuild-iptables failing on debian

### ISSUE THREAD

**Issue by pduersteler** [chef-cookbooks/iptables#57] opened 2016-05-23 18:33 UTC
### Cookbook version
Current master branch at 32bbecd

### Chef-client version
Chef: 12.10.24

### Platform Details
Developing on OS X, client runs Debian GNU/Linux 8.4 (jessie)

### Scenario:
Rules are not applied to iptables. The rule files are put in /etc/iptables.d/, but are not being loaded due to an error thrown by rebuild-iptables.

### Steps to Reproduce:
 * Add `cookbook 'iptables', github: 'chef-cookbooks/iptables'`` to Berksfile
 * Add `depends 'iptables'` to metadata.rb
 * Add `iptables_rule 'http_80' { lines '-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT' }`
 * Run `kitchen converge`
 * See missing rules when executing `iptables -L`
 * SSH into client and manually run `rebuild-iptables` to try
 * See that rules are still missing when executing `iptables -L`

### Expected Result:
`iptables -L` should display rules, and manually running `rebuild-iptables` should not throw an error.

### Actual Result:
When running `rebuild-iptables`, the following error message is displayed:
```
Bad argument `{IP6TABLES_MODULES'
Error occurred at line: 7
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
cp: cannot create regular file '/etc/sysconfig/iptables': No such file or directory
```

Also, there is no /etc/sysconfig on jessie.

**Comment by shubhamitc** [comment] 2016-09-21 12:01
This is because you are using iptables attribute set and these attributes are added. 
Create another attribute set like default['iptables']['rules'] and iterate over that. That should solve this issue.

**Comment by lamont-granquist** [comment] 2016-10-11 02:21
closing this as its over 6 months old now and seems to not be a bug

**Closed by lamont-granquist** 2016-10-11 02:21 UTC

**Comment by hedgehog** [comment] 2016-10-28 09:05
I've run into the same issue.  My recipe file has:
````
iptables_rule 'vpn_forward' do
  lines '-I FORWARD -j ACCEPT'
end
````

the file is created with correct content in `/etc/iptables.d/vpn_nat`

Hope I've not done anything silly?

**Comment by dpnsan** [comment] 2016-11-02 15:49
This issue is also affecting me. The cause is that Ubuntu does not use /etc/sysconfig, and my tests fail in Ubuntu 14.04 for this reason. The correct location would be /etc/network. The previous iteration of this script created an /etc/iptables directory for this purpose, which would also work.

**Comment by hedgehog** [comment] 2016-11-04 02:05
@lamont-granquist is this worth re-opening?

**Comment by lamont-granquist** [comment] 2016-11-04 19:04
I don't see how @dpnsan's comment relates to the other error messages here or how it relates to the refactoring of the iptables cookbook in https://github.com/chef-cookbooks/iptables/commit/d8b00099b143702ac2c9534cfb95acca609444c7 which seems to still leave the /etc/iptables/general file in place, so i can't see how that broke anything.

At this point it would be better to open a PR to show me rather than tell me, because IDK what to fix here.

**Comment by congaframe** [comment] 2017-04-10 15:19
I'm having the same issue on Debian 7 ( Test Kitchen). I tried the recommended rule on README:
```
iptables_rule 'http_8080' do
  lines '-A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080'
end
```
then manually run this command to load it : 
`/sbin/iptables-restore < /etc/iptables/general`
which failed on line 7 ( COMMIT)
It seems the file `/etc/iptables/general` is written in incorrect format. 
I used template and it works fine.
